from . import (
    about,
    admin,
    category_handler,
    faq_handler,
    feedback_handler,
    help,
    lessons_handler,
    main_menu_handler,
    questions_handler,
    start,
    statistics_handler,
    subscription_handler,
    videos_handler,
)
